blank_issues_enabled: false
contact_links:
- name: Discussion board
<<<<<<< HEAD
  url: https://github.com/pypsa-meets-earth/pypsa-earth/discussions
=======
  url: https://github.com/pypsa-meets-earth/pypsa-distribution/discussions
>>>>>>> distribution/the_changes_for_fork_v1
  about: Please ask and answer general usage questions here.
